import type { LanguageEntry } from './types.js';

// ─── Tier 1 — Full Ecosystem (17 languages) ────────────────────────────────

const nodeSkipDirs = [
  'node_modules', 'dist', 'build', 'out',
  '.next', '.nuxt', '.svelte-kit', '.turbo', '.cache', '.parcel-cache',
];

const tier1: LanguageEntry[] = [
  {
    name: 'TypeScript',
    extensions: ['.ts', '.tsx', '.mts', '.cts'],
    tier: 1,
    skipDirs: nodeSkipDirs,
    entryPoints: [
      'src/index.ts', 'src/main.ts', 'src/app.ts', 'src/server.ts',
      'index.ts', 'main.ts',
    ],
    packageFiles: ['package.json', 'tsconfig.json'],
  },
  {
    name: 'JavaScript',
    extensions: ['.js', '.jsx', '.mjs', '.cjs'],
    tier: 1,
    skipDirs: nodeSkipDirs,
    entryPoints: [
      'src/index.js', 'src/main.js', 'src/app.js', 'src/server.js',
      'index.js', 'main.js',
    ],
    packageFiles: ['package.json'],
  },
  {
    name: 'Python',
    extensions: ['.py', '.pyw', '.pyi'],
    tier: 1,
    skipDirs: [
      '__pycache__', '.venv', 'venv', '.mypy_cache',
      '.pytest_cache', '.tox', 'htmlcov', '.eggs',
    ],
    entryPoints: ['main.py', 'app.py', 'src/main.py', 'src/app.py', 'manage.py'],
    packageFiles: ['pyproject.toml', 'setup.py', 'setup.cfg', 'requirements.txt', 'Pipfile'],
  },
  {
    name: 'Go',
    extensions: ['.go'],
    tier: 1,
    skipDirs: ['vendor'],
    entryPoints: ['main.go', 'cmd/main.go', 'cmd/server/main.go'],
    packageFiles: ['go.mod'],
  },
  {
    name: 'Rust',
    extensions: ['.rs'],
    tier: 1,
    skipDirs: ['target'],
    entryPoints: ['src/main.rs', 'src/lib.rs'],
    packageFiles: ['Cargo.toml'],
  },
  {
    name: 'Java',
    extensions: ['.java'],
    tier: 1,
    skipDirs: ['target', '.gradle', '.mvn', 'bin', 'out'],
    entryPoints: [
      'src/main/java/Main.java', 'src/main/java/App.java',
      'src/main/java/Application.java',
    ],
    packageFiles: ['pom.xml', 'build.gradle', 'build.gradle.kts'],
  },
  {
    name: 'Kotlin',
    extensions: ['.kt', '.kts'],
    tier: 1,
    skipDirs: ['target', '.gradle', 'bin', 'out'],
    entryPoints: ['src/main/kotlin/Main.kt', 'src/main/kotlin/App.kt'],
    packageFiles: ['build.gradle.kts', 'build.gradle', 'pom.xml'],
  },
  {
    name: 'Ruby',
    extensions: ['.rb', '.rake', '.gemspec'],
    tier: 1,
    skipDirs: ['vendor', '.bundle'],
    entryPoints: ['app.rb', 'main.rb', 'config.ru', 'lib/main.rb'],
    packageFiles: ['Gemfile'],
  },
  {
    name: 'PHP',
    extensions: ['.php'],
    tier: 1,
    skipDirs: ['vendor'],
    entryPoints: ['index.php', 'public/index.php', 'artisan'],
    packageFiles: ['composer.json'],
  },
  {
    name: 'C#',
    extensions: ['.cs', '.csx'],
    tier: 1,
    skipDirs: ['bin', 'obj', '.vs'],
    entryPoints: ['Program.cs', 'src/Program.cs'],
    packageFiles: ['*.csproj', '*.sln'],
  },
  {
    name: 'Swift',
    extensions: ['.swift'],
    tier: 1,
    skipDirs: ['.build', '.swiftpm', 'DerivedData'],
    entryPoints: ['Sources/main.swift', 'Sources/App/main.swift'],
    packageFiles: ['Package.swift'],
  },
  {
    name: 'Dart',
    extensions: ['.dart'],
    tier: 1,
    skipDirs: ['.dart_tool', 'build', '.flutter-plugins'],
    entryPoints: ['lib/main.dart', 'bin/main.dart'],
    packageFiles: ['pubspec.yaml'],
  },
  {
    name: 'Elixir',
    extensions: ['.ex', '.exs'],
    tier: 1,
    skipDirs: ['_build', 'deps', '.elixir_ls'],
    entryPoints: ['lib/application.ex', 'lib/app.ex'],
    packageFiles: ['mix.exs'],
  },
  {
    name: 'Scala',
    extensions: ['.scala', '.sc'],
    tier: 1,
    skipDirs: ['target', '.bsp', '.metals', 'project/target'],
    entryPoints: ['src/main/scala/Main.scala'],
    packageFiles: ['build.sbt', 'build.sc'],
  },
  {
    name: 'C++',
    extensions: ['.cpp', '.hpp', '.cc', '.cxx', '.hxx', '.h'],
    tier: 1,
    skipDirs: ['build', 'cmake-build-debug', 'cmake-build-release'],
    entryPoints: ['src/main.cpp', 'main.cpp'],
    packageFiles: ['CMakeLists.txt', 'Makefile', 'conanfile.txt', 'vcpkg.json'],
  },
  {
    name: 'C',
    extensions: ['.c'],
    tier: 1,
    skipDirs: ['build', 'cmake-build-debug', 'cmake-build-release'],
    entryPoints: ['src/main.c', 'main.c'],
    packageFiles: ['CMakeLists.txt', 'Makefile'],
  },
  {
    name: 'Zig',
    extensions: ['.zig'],
    tier: 1,
    skipDirs: ['zig-cache', 'zig-out'],
    entryPoints: ['src/main.zig', 'src/root.zig'],
    packageFiles: ['build.zig', 'build.zig.zon'],
  },
];

// ─── Tier 2 — Package Manager + Test Runner (21 languages) ─────────────────

const tier2: LanguageEntry[] = [
  {
    name: 'Haskell',
    extensions: ['.hs', '.lhs'],
    tier: 2,
    skipDirs: ['.stack-work', 'dist-newstyle', 'dist'],
    entryPoints: ['app/Main.hs', 'src/Main.hs'],
    packageFiles: ['package.yaml', '*.cabal', 'stack.yaml'],
  },
  {
    name: 'Clojure',
    extensions: ['.clj', '.cljs', '.cljc', '.edn'],
    tier: 2,
    skipDirs: ['target', '.cpcache', '.clj-kondo'],
    entryPoints: ['src/core.clj', 'src/main.clj'],
    packageFiles: ['deps.edn', 'project.clj', 'build.clj'],
  },
  {
    name: 'F#',
    extensions: ['.fs', '.fsi', '.fsx'],
    tier: 2,
    skipDirs: ['bin', 'obj', '.vs'],
    entryPoints: ['Program.fs', 'src/Program.fs'],
    packageFiles: ['*.fsproj', '*.sln'],
  },
  {
    name: 'OCaml',
    extensions: ['.ml', '.mli'],
    tier: 2,
    skipDirs: ['_build', '_opam'],
    entryPoints: ['bin/main.ml', 'src/main.ml'],
    packageFiles: ['dune-project', '*.opam'],
  },
  {
    name: 'Nim',
    extensions: ['.nim', '.nims', '.nimble'],
    tier: 2,
    skipDirs: ['nimcache', 'nimble'],
    entryPoints: ['src/main.nim', 'main.nim'],
    packageFiles: ['*.nimble'],
  },
  {
    name: 'Crystal',
    extensions: ['.cr'],
    tier: 2,
    skipDirs: ['lib', '.shards'],
    entryPoints: ['src/main.cr', 'src/app.cr'],
    packageFiles: ['shard.yml'],
  },
  {
    name: 'Julia',
    extensions: ['.jl'],
    tier: 2,
    skipDirs: ['.julia'],
    entryPoints: ['src/main.jl', 'main.jl'],
    packageFiles: ['Project.toml', 'Manifest.toml'],
  },
  {
    name: 'Perl',
    extensions: ['.pl', '.pm', '.t'],
    tier: 2,
    skipDirs: ['blib', '.build'],
    entryPoints: ['script/main.pl', 'bin/main.pl', 'lib/App.pm'],
    packageFiles: ['Makefile.PL', 'Build.PL', 'cpanfile', 'dist.ini'],
  },
  {
    name: 'Lua',
    extensions: ['.lua'],
    tier: 2,
    skipDirs: ['lua_modules', '.luarocks'],
    entryPoints: ['main.lua', 'init.lua', 'src/main.lua'],
    packageFiles: ['*.rockspec', '.luacheckrc'],
  },
  {
    name: 'R',
    extensions: ['.r', '.R', '.Rmd', '.Rnw'],
    tier: 2,
    skipDirs: ['.Rproj.user', 'renv'],
    entryPoints: ['main.R', 'app.R', 'R/main.R'],
    packageFiles: ['DESCRIPTION', 'renv.lock'],
  },
  {
    name: 'Erlang',
    extensions: ['.erl', '.hrl'],
    tier: 2,
    skipDirs: ['_build', '.rebar3'],
    entryPoints: ['src/app.erl', 'src/main.erl'],
    packageFiles: ['rebar.config', 'erlang.mk'],
  },
  {
    name: 'Groovy',
    extensions: ['.groovy', '.gvy', '.gy'],
    tier: 2,
    skipDirs: ['build', '.gradle', 'target'],
    entryPoints: ['src/main/groovy/Main.groovy', 'src/main/groovy/App.groovy'],
    packageFiles: ['build.gradle', 'build.gradle.kts', 'pom.xml'],
  },
  {
    name: 'V',
    extensions: ['.v'],
    tier: 2,
    skipDirs: ['.cache'],
    entryPoints: ['main.v', 'src/main.v'],
    packageFiles: ['v.mod'],
  },
  {
    name: 'Objective-C',
    extensions: ['.m', '.mm'],
    tier: 2,
    skipDirs: ['build', 'DerivedData', 'Pods'],
    entryPoints: ['main.m', 'Sources/main.m'],
    packageFiles: ['Podfile', '*.xcodeproj'],
  },
  {
    name: 'D',
    extensions: ['.d'],
    tier: 2,
    skipDirs: ['.dub'],
    entryPoints: ['source/app.d', 'source/main.d', 'src/main.d'],
    packageFiles: ['dub.json', 'dub.sdl'],
  },
  {
    name: 'Ada',
    extensions: ['.adb', '.ads'],
    tier: 2,
    skipDirs: ['obj', 'lib'],
    entryPoints: ['src/main.adb', 'main.adb'],
    packageFiles: ['*.gpr', 'alire.toml'],
  },
  {
    name: 'Fortran',
    extensions: ['.f90', '.f95', '.f03', '.f08', '.f'],
    tier: 2,
    skipDirs: ['build'],
    entryPoints: ['src/main.f90', 'app/main.f90'],
    packageFiles: ['fpm.toml', 'CMakeLists.txt', 'Makefile'],
  },
  {
    name: 'COBOL',
    extensions: ['.cob', '.cbl', '.cpy'],
    tier: 2,
    skipDirs: ['bin', 'build'],
    entryPoints: ['src/main.cob', 'main.cob'],
    packageFiles: ['Makefile'],
  },
  {
    name: 'Hack',
    extensions: ['.hack', '.hh'],
    tier: 2,
    skipDirs: ['vendor'],
    entryPoints: ['src/main.hack', 'main.hack'],
    packageFiles: ['.hhconfig', 'composer.json'],
  },
  {
    name: 'Gleam',
    extensions: ['.gleam'],
    tier: 2,
    skipDirs: ['build'],
    entryPoints: ['src/app.gleam', 'src/main.gleam'],
    packageFiles: ['gleam.toml'],
  },
  {
    name: 'Assembly',
    extensions: ['.asm', '.s', '.S'],
    tier: 2,
    skipDirs: ['build', 'obj'],
    entryPoints: ['src/main.asm', 'main.asm'],
    packageFiles: ['Makefile'],
  },
];

// ─── Tier 3 — Extension Only (18 languages) ────────────────────────────────

const tier3: LanguageEntry[] = [
  {
    name: 'Lisp',
    extensions: ['.lisp', '.lsp', '.cl', '.asd'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Scheme',
    extensions: ['.scm', '.ss'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Racket',
    extensions: ['.rkt'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Prolog',
    extensions: ['.pro'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Forth',
    extensions: ['.fth', '.4th'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'APL',
    extensions: ['.apl', '.dyalog'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'VHDL',
    extensions: ['.vhd', '.vhdl'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Verilog',
    extensions: ['.sv', '.svh'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Tcl',
    extensions: ['.tcl'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Shell',
    extensions: ['.sh', '.bash', '.zsh'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'PowerShell',
    extensions: ['.ps1', '.psm1', '.psd1'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Terraform',
    extensions: ['.tf', '.hcl'],
    tier: 3,
    skipDirs: ['.terraform'],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Solidity',
    extensions: ['.sol'],
    tier: 3,
    skipDirs: ['artifacts', 'cache'],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Move',
    extensions: ['.move'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Cairo',
    extensions: ['.cairo'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'GraphQL',
    extensions: ['.graphql', '.gql'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'Protobuf',
    extensions: ['.proto'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
  {
    name: 'SQL',
    extensions: ['.sql'],
    tier: 3,
    skipDirs: [],
    entryPoints: [],
    packageFiles: [],
  },
];

// ─── Export ──────────────────────────────────────────────────────────────────

export const LANGUAGES: LanguageEntry[] = [...tier1, ...tier2, ...tier3];
